version: "3.9"

services:
  ecommerce:
    build: .
    container_name: ecommerce-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
